### ISSUE TITLE
Running Build.PL generates warning about missing META.json

### ISSUE THREAD

**Issue by jkeenan** [schwern/Test-Sims#1]
Demonstration:
```
$ perl Build.PL
WARNING: the following files are missing in your kit:
	META.json
Please inform the author.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Test-Sims' version '20130412'
```
You **do** have a ```MYMETA.json``` file in your distribution:
```
[Test-Sims] 525 $ ls
_build  Build.PL  inc  MANIFEST       META.yml     MYMETA.yml  t
Build   Changes   lib  MANIFEST.SKIP  MYMETA.json  README
```
But your ```MANIFEST``` is expecting ```META.json```:
```
$ grep -n META MANIFEST
9:META.json
10:META.yml
```
(Since I don't use Module::Build myself, I'm not sure what the best way to correct this is.)

Thank you very much.
Jim Keenan

**Comment by schwern** [comment]
Thanks for the report. I just forgot to generate that file. All fixed! A new version is on its way to CPAN.
