### ISSUE TITLE
Tests fail with perl 5.27.6 and later

### ISSUE THREAD

**Issue by eserte** [schwern/Test-Sims#2]
See http://fast-matrix.cpantesters.org/?dist=Test-Sims%2020180103 for an overview. A sample fail report: http://fast-matrix.cpantesters.org/?dist=Test-Sims%2020180103

This is probably the same issue as discussed in https://rt.perl.org/Ticket/Display.html?id=132252

**Comment by eserte** [comment]
https://github.com/schwern/Test-Sims/pull/3 should address the issue.

**Comment by schwern** [comment]
Fixed by #3.

**Comment by mauke** [comment]
@schwern Could you release the fix on CPAN?
